In [3]:
## Truncated Gaussian Distribution

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append('../')
from game.Bankgames import *
from game.plotting import *
from game.distributions import TruncatedGaussian, Uniform, PiecewiseUniform
import nashpy as nh

In [7]:
# Truncated gaussian
tg = TruncatedGaussian()
gammas = [0.5, 0.6]

taus = [1/(2+gamma) for gamma in gammas]

game_tg = GameTrueMatrix2by2(gammas = gammas, taus = taus, dist = tg)

In [8]:
game_tg.eps1, game_tg.eps2

(-0.23058161945446387, -0.25748629749030433)

In [9]:
game_tg.NE_theory

[[[0, 0, 1, 0], [0, 0, 1, 0]]]

In [10]:
game_tg.NE_se

[(array([0., 0., 1., 0.]), array([0., 0., 1., 0.]))]

In [13]:
T = 10000
p_b1 = np.array([0., 0.4, 0.7, 0.])
p_b2 = np.array([0., 0.5, 0.3, 0.])
eta = 0.1

p_b1, p_b2, _, _ = game_tg.run_hedge(T=T, p_b1 = p_b1, p_b2 = p_b2, eta=eta)
print(p_b1[-1], p_b2[-1])

In [15]:
game_tg.get_closest_elementwise_NE(p_b1[-1], p_b2[-1])

[(array([0., 0., 1., 0.]), array([0., 0., 1., 0.]))]

In [5]:
# Piecewise uniform
gammas = [0.5, 0.6]
taus = [1/(2+gamma) for gamma in gammas]
puf = PiecewiseUniform()
game_puf = GameTrueMatrix2by2(gammas = gammas, taus = taus, dist = puf)

In [6]:
game_puf.NE_theory

[[[0, 1, 0, 0], [0, 0, 1, 0]],
 [[0, 0, 1, 0], [0, 1, 0, 0]],
 [[0, 0.08028259473346401, 0.919717405266536, 0],
  [0, 0.08028259473346401, 0.919717405266536, 0]]]

In [15]:
game_puf.NE_se

[(array([0., 1., 0., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 1., 0., 0.])),
 (array([0.        , 0.08028259, 0.91971741, 0.        ]),
  array([0.        , 0.08028259, 0.91971741, 0.        ]))]

In [30]:
T = 10000


p_b1, p_b2, _, _ = game_puf.run_hedge(T=T, p_b1 = p_b1, p_b2 = p_b2, eta=eta)

In [31]:
p_b1[-1], p_b2[-1]

(array([0.        , 0.00119503, 0.99880497, 0.        ]),
 array([0.        , 0.72071293, 0.27928707, 0.        ]))

In [18]:
p_b1.shape, p_b1[-1], p_b2[-1]

((100001, 4),
 array([0.00000000e+00, 7.22207234e-30, 1.00000000e+00, 0.00000000e+00]),
 array([0.        , 0.99860184, 0.00139816, 0.        ]))

In [28]:
# game_puf.get_closest_elementwise_NE(p_b1[-1], p_b2[-1])

# PLOTS TODO n = 4 actions

1) Known Matrix, Full matrix known


Game with n = 4 actions (2 gammas) 
4 cases for epsilon_1, epsilon_2

Dynamics curves, show indifferent to initialization 

- epsilon_1>0, epsilon_2>0 ; 1 pure NE
- epsilon_1<0, epsilon_2<0 1 pure NE
- 3 cases for different signs (-,+)
- 3 cases for different signs (+, -)

---

1) Sampled Matrix (Fresh matrix estimated in each round) 

Game with n = 4 actions (2 gammas) 
4 cases for epsilon_1, epsilon_2

Dynamics curves, show indifferent to initialization 

- 1 pure NE
- 1 pure NE
- 3 cases for different signs (-,+)
- 3 cases for different signs (+,-)
 
Fraction of convergence plots
- Fix distribution, fix gamma (defines an instance of the one-shot game)
- For a fixed initilaization, check convergence across randomness in sampling (fresh estimate for A)
- Fix distribution, fix gamma, for some fixed initilaization, check distance to NE across randomness in sampling (fresh estimate for A)


- For a fixed initilaization, check convergence check convergence across randomness in sampling (moving estimate for A)
- Fix distribution, fix gamma, for some fixed initilaization, check distance to NE across randomness in sampling (moving estimate for A)

In [29]:
# PLOTS TODO for larger number of actions

vary distribution (fix truncated gaussian some values)
precified values of gamma
vary initializations